runtime: nodejs18

handlers:
- url: /googledce38e530879d696\.html
  static_files: static/googledce38e530879d696.html
  upload: static/googledce38e530879d696\.html
  expiration: "7d"
  secure: always
  redirect_http_response_code: 301
  http_headers:
    Referrer-Policy: no-referrer-when-downgrade
    Feature-Policy: sync-xhr 'none'; camera 'none'; microphone 'none';
    X-Frame-Options: 'SAMEORIGIN'
    X-Content-Type-Options: 'nosniff'
    Strict-Transport-Security: max-age=31536000; includeSubDomains

- url: /assets/css/(.*\.css)$
  mime_type: text/css
  static_files: src/assets/css/\1
  upload: src/assets/css/.*\.css$
  expiration: "7d"
  secure: always
  redirect_http_response_code: 301
  http_headers:
    Referrer-Policy: no-referrer-when-downgrade
    Feature-Policy: sync-xhr 'none'; camera 'none'; microphone 'none';
    X-Frame-Options: 'SAMEORIGIN'
    X-Content-Type-Options: 'nosniff'
    Strict-Transport-Security: max-age=31536000; includeSubDomains

- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon\.ico
  expiration: "7d"
  secure: always
  redirect_http_response_code: 301
  http_headers:
    Referrer-Policy: no-referrer-when-downgrade
    Feature-Policy: sync-xhr 'none'; camera 'none'; microphone 'none';
    X-Frame-Options: 'SAMEORIGIN'
    X-Content-Type-Options: 'nosniff'
    Strict-Transport-Security: max-age=31536000; includeSubDomains

- url: /
  static_files: src/index.html
  upload: src/index\.html
  expiration: "3d"
  secure: always
  redirect_http_response_code: 301
  http_headers:
    Referrer-Policy: no-referrer-when-downgrade
    Feature-Policy: sync-xhr 'none'; camera 'none'; microphone 'none';
    X-Frame-Options: 'SAMEORIGIN'
    X-Content-Type-Options: 'nosniff'
    Strict-Transport-Security: max-age=31536000; includeSubDomains


- url: /.*
  static_files: src/404.html
  upload: src/404\.html
  expiration: "3d"
  secure: always
  redirect_http_response_code: 301
  http_headers:
    Referrer-Policy: no-referrer-when-downgrade
    Feature-Policy: sync-xhr 'none'; camera 'none'; microphone 'none';
    X-Frame-Options: 'SAMEORIGIN'
    X-Content-Type-Options: 'nosniff'
    Strict-Transport-Security: max-age=31536000; includeSubDomains
