runtime: nodejs12

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico
  expiration: "7d"
  secure: always
  redirect_http_response_code: 301
  http_headers:
    Content-Security-Policy: script-src 'self'
    Referrer-Policy: no-referrer-when-downgrade
    Feature-Policy: sync-xhr 'none'; camera 'none'; microphone 'none';
    X-Frame-Options: 'SAMEORIGIN'
    X-Content-Type-Options: 'nosniff'
    Strict-Transport-Security: max-age=31536000; includeSubDomains

- url: /googledce38e530879d696\.html
  static_files: googledce38e530879d696.html
  upload: googledce38e530879d696\.html
  expiration: "7d"
  secure: always
  redirect_http_response_code: 301
  http_headers:
    Content-Security-Policy: script-src 'self'
    Referrer-Policy: no-referrer-when-downgrade
    Feature-Policy: sync-xhr 'none'; camera 'none'; microphone 'none';
    X-Frame-Options: 'SAMEORIGIN'
    X-Content-Type-Options: 'nosniff'
    Strict-Transport-Security: max-age=31536000; includeSubDomains

- url: /assets/styles/screen\.css
  mime_type: text/css
  static_files: assets/styles/screen.css
  upload: assets/styles/screen.css
  expiration: "7d"
  secure: always
  redirect_http_response_code: 301
  http_headers:
    Content-Security-Policy: script-src 'self'
    Referrer-Policy: no-referrer-when-downgrade
    Feature-Policy: sync-xhr 'none'; camera 'none'; microphone 'none';
    X-Frame-Options: 'SAMEORIGIN'
    X-Content-Type-Options: 'nosniff'
    Strict-Transport-Security: max-age=31536000; includeSubDomains

- url: /assets/fonts/peterlagerstrom-icons\.woff
  static_files: assets/fonts/peterlagerstrom-icons.woff
  upload: assets/fonts/peterlagerstrom-icons\.woff
  expiration: "7d"
  secure: always
  redirect_http_response_code: 301
  http_headers:
    Content-Security-Policy: script-src 'self'
    Referrer-Policy: no-referrer-when-downgrade
    Feature-Policy: sync-xhr 'none'; camera 'none'; microphone 'none';
    X-Frame-Options: 'SAMEORIGIN'
    X-Content-Type-Options: 'nosniff'
    Strict-Transport-Security: max-age=31536000; includeSubDomains

- url: /assets/fonts/peterlagerstrom-icons\.ttf
  static_files: assets/fonts/peterlagerstrom-icons.ttf
  upload: assets/fonts/peterlagerstrom-icons\.ttf
  expiration: "7d"
  secure: always
  redirect_http_response_code: 301
  http_headers:
    Content-Security-Policy: script-src 'self'
    Referrer-Policy: no-referrer-when-downgrade
    Feature-Policy: sync-xhr 'none'; camera 'none'; microphone 'none';
    X-Frame-Options: 'SAMEORIGIN'
    X-Content-Type-Options: 'nosniff'
    Strict-Transport-Security: max-age=31536000; includeSubDomains

- url: /assets/fonts/peterlagerstrom-icons\.svg
  static_files: assets/fonts/peterlagerstrom-icons.svg
  upload: assets/fonts/peterlagerstrom-icons\.svg
  expiration: "7d"
  secure: always
  redirect_http_response_code: 301
  http_headers:
    Content-Security-Policy: script-src 'self'
    Referrer-Policy: no-referrer-when-downgrade
    Feature-Policy: sync-xhr 'none'; camera 'none'; microphone 'none';
    X-Frame-Options: 'SAMEORIGIN'
    X-Content-Type-Options: 'nosniff'
    Strict-Transport-Security: max-age=31536000; includeSubDomains

- url: /assets/fonts/peterlagerstrom-icons\.eot
  static_files: assets/fonts/peterlagerstrom-icons.eot
  upload: assets/fonts/peterlagerstrom-icons\.eot
  expiration: "7d"
  secure: always
  redirect_http_response_code: 301
  http_headers:
    Content-Security-Policy: script-src 'self'
    Referrer-Policy: no-referrer-when-downgrade
    Feature-Policy: sync-xhr 'none'; camera 'none'; microphone 'none';
    X-Frame-Options: 'SAMEORIGIN'
    X-Content-Type-Options: 'nosniff'
    Strict-Transport-Security: max-age=31536000; includeSubDomains

- url: /.*
  static_files: index.html
  upload: index\.html
  expiration: "3d"
  secure: always
  redirect_http_response_code: 301
  http_headers:
    Content-Security-Policy: script-src 'self'
    Referrer-Policy: no-referrer-when-downgrade
    Feature-Policy: sync-xhr 'none'; camera 'none'; microphone 'none';
    X-Frame-Options: 'SAMEORIGIN'
    X-Content-Type-Options: 'nosniff'
    Strict-Transport-Security: max-age=31536000; includeSubDomains
